version: '3.1'

services:
    db:
        image: mdillon/postgis:11
        restart: always
        volumes:
            - db:/var/lib/postgresql/data
        expose:
            - 5432

    mongo:
        image: mongo:latest
        restart: always
        #command: --wiredTigerCacheSizeGB 4.0
        volumes:
            - mongo:/data/db
        expose:
            - 27017

    wx_explore:
        image: kallsyms/wx_explore:latest
        restart: always
        depends_on:
            - db
            - mongo
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=db
            - DATA_PROVIDER=MONGO
            - INGEST_MONGO_SERVER_URI=mongodb://mongo:27017/
            - INGEST_MONGO_DATABASE=wx
            - INGEST_MONGO_COLLECTION=wx
            - TRACE_EXPORTER=honeycomb
            - HONEYCOMB_DATASET=prod
            - HONEYCOMB_API_KEY
        volumes:
            - ./:/opt/wx_explore
        ports:
            - "80:8080"

volumes:
    db:
    mongo:
