version: "3.1"

services:
  db:
    image: mdillon/postgis:11
    restart: always
    expose:
      - 5432
    ports:
      - "5464:5432"

  mongo:
    image: mongo:latest
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"

  jaeger:
    image: jaegertracing/all-in-one:latest
    expose:
      - 6831
    ports:
      - "16686:16686"
