version: '3.1'

services:
    db:
        image: mdillon/postgis:11
        restart: always
        expose:
            - 5432

    mongo:
        image: mongo:latest
        restart: always
        expose:
            - 27017

    jaeger:
        image: jaegertracing/all-in-one:latest
        expose:
            - 6831
        ports:
            - "16686:16686"

    wx_explore:
        image: wx_explore:latest
        build: .
        restart: always
        depends_on:
            - db
            - mongo
            - jaeger
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=db
            - DATA_PROVIDER=MONGO
            - INGEST_MONGO_SERVER_URI=mongodb://mongo:27017/
            - INGEST_MONGO_DATABASE=wx
            - INGEST_MONGO_COLLECTION=wx
            - TRACE_EXPORTER=jaeger
            - JAEGER_HOST=jaeger
        volumes:
            - ./:/opt/wx_explore
        ports:
            - "8080:8080"
        command: tail -f /dev/null
