version: '3.1'

services:
    db:
        # https://github.com/postgis/docker-postgis/issues/216
        image: ghcr.io/baosystems/postgis:13-3.2
        restart: always
        volumes:
            - db:/var/lib/postgresql/data
        expose:
            - 5432

    mongo:
        image: mongo:latest
        restart: always
        command: --logpath /dev/null
        volumes:
            - mongo:/data/db
        expose:
            - 27017

    wx_explore:
        image: kallsyms/wx_explore:latest
        restart: always
        depends_on:
            - db
            - mongo
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=db
            - DATA_PROVIDER=MONGO
            - INGEST_MONGO_SERVER_URI=mongodb://mongo:27017/
            - INGEST_MONGO_DATABASE=wx
            - INGEST_MONGO_COLLECTION=wx
        ports:
            - "80:8080"

volumes:
    db:
    mongo:
