name: CI

on: [push]
jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          builds_args: BUILDKIT_INLINE_CACHE=1
          cache_froms: ghcr.io/${{ github.repository }}:latest
          tag_with_ref: true
          tag_with_sha: true
